name: Docker Build and Test

on:
  push:
    branches: [main, develop]
    paths:
      - 'ui/**'
      - 'analysis/**'
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
      - 'ui/Dockerfile'
  pull_request:
    branches: [main, develop]
    paths:
      - 'ui/**'
      - 'analysis/**'
      - 'Dockerfile'
      - 'ui/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ui/Dockerfile
          push: false
          load: true
          tags: ncsoccer-ui:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          # Create test environment variables
          echo "ANTHROPIC_API_KEY=test-key" > .env.test
          echo "BASIC_AUTH_USERNAME=test-user" >> .env.test
          echo "BASIC_AUTH_PASSWORD=test-password" >> .env.test

          # Run container in detached mode
          docker run -d --name ncsoccer-test --env-file .env.test -p 8501:8501 ncsoccer-ui:test

          # Wait for container to start
          sleep 10

          # Check if container is running
          docker ps | grep ncsoccer-test

          # Check if Streamlit health endpoint is accessible
          curl --silent --fail http://localhost:8501/_stcore/health || exit 1

          # Display container logs for debugging
          docker logs ncsoccer-test

          # Stop and remove container
          docker stop ncsoccer-test
          docker rm ncsoccer-test